/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Community;
import model.CommunityDirectory;

/**
 *
 * @author siddh
 */
public class SysAdminCreateCommunityPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminCreateCommunityPanel
     */
    CommunityDirectory communityDirectory;
    Community community;
    String mainValidationString = "";
    String validationString1 = "";
    
    public SysAdminCreateCommunityPanel(CommunityDirectory communityDirectory) {
        initComponents();
        this.communityDirectory = communityDirectory;
    }
    
    public SysAdminCreateCommunityPanel(CommunityDirectory communityDirectory, Community community) {
        initComponents();
        this.communityDirectory = communityDirectory;
        this.community = community;
        setSysAdminCreateCommunityPanel();
    }

    private void setSysAdminCreateCommunityPanel() {
        txtCommunityId.setText(community.getId());
        txtCommunityName.setText(community.getName());
    }

    private void resetCommunityData() {
        txtCommunityId.setText("");
        txtCommunityName.setText("");
    }

    private Community setCommunityData() {
        String communityId = txtCommunityId.getText();
        String communityName = txtCommunityName.getText();
        Community community = new Community();
        community.setId(communityId);
        community.setName(communityName);
        return community;
    }
    
     public boolean areDataFieldsEmpty() {
        validationString1 = "";
        if (txtCommunityId.getText().isEmpty()) {
            validationString1 += "Community Id, ";
        }
        if (txtCommunityName.getText().isEmpty()) {
            validationString1 += "Community Name, ";
        }
        return isNotValid(validationString1);
    }

    public boolean isNotValid(String str) {
        if (str.equals("")) {
            return false;
        } else {
            return true;
        }
    }

    public void validationErrorMessagesDialog() {
        mainValidationString = validationString1;
        JOptionPane.showMessageDialog(this, "Please update the data for these fields: " + mainValidationString);
    }

    public boolean communityDetailsExistence() {
        String communityId = txtCommunityId.getText();
        boolean exist = false;
        for (Community com : communityDirectory.getCommunities()) {
            if (communityId.equals(com.getId())) {
                exist = true;
                break;
            }
        }
        return exist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCommunityId = new javax.swing.JTextField();
        txtCommunityName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        btnCreate.setText("CREATE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Community ID");

        jLabel2.setText("Community Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("DETAILS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCommunityId)
                    .addComponent(txtCommunityName, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnCreate)
                        .addGap(59, 59, 59)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnBack)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommunityId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
         boolean validation1 = areDataFieldsEmpty();

        if (!validation1) {
            String communityId = txtCommunityId.getText();
            if (!communityDetailsExistence()) {
                communityDirectory.addCommunity(setCommunityData());
                JOptionPane.showMessageDialog(this, "New community with community id : " + communityId + " created");
                resetCommunityData();
                SysAdminCreateCommunitiesJFrame.refreshSysAdminViewCommunityPanel(communityDirectory);
            } else {
                JOptionPane.showMessageDialog(this, "Community details already exists with the community id : " + communityId);
            }
        } else {
            validationErrorMessagesDialog();
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         String communityId = txtCommunityId.getText();

        boolean validation1 = areDataFieldsEmpty();
        if (!validation1) {
            if (!communityDetailsExistence()) {
                JOptionPane.showMessageDialog(this, "You can't update the community details since community id : " + communityId + " doesn't exist");
            } else {
                Community community = setCommunityData();
                int index = 0;
                for (Community com : communityDirectory.getCommunities()) {
                    if (com.getId().equals(communityId)) {
                        communityDirectory.updateCommunity(community, index);
                        break;
                    }
                    index++;
                }
                JOptionPane.showMessageDialog(this, "Existing community details with community id : " + communityId + " updated");
                resetCommunityData();
                SysAdminCreateCommunitiesJFrame.refreshSysAdminViewCommunityPanel(communityDirectory);
            }
        } else {
            validationErrorMessagesDialog();
        }
        
        
//        String communityId = txtCommunityId.getText();
//        Community community = setCommunityData();
//        int index = 0;
//        for (Community com : communityDirectory.getCommunities()) {
//            if (com.getId().equals(communityId)) {
//                communityDirectory.updateCommunity(community, index);
//                break;
//            }
//            index++;
//        }
//        JOptionPane.showMessageDialog(this, "Existing community with employee id : " + communityId + " updated");
//        resetCommunityData();
//        SysAdminCreateCommunitiesJFrame.refreshSysAdminViewCommunityPanel(communityDirectory);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SysAdminCreateCommunitiesJFrame.closeFrame();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCommunityId;
    private javax.swing.JTextField txtCommunityName;
    // End of variables declaration//GEN-END:variables
}
