/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.Patient;
import model.PatientDirectory;
import model.Person;
/**
 *
 * @author siddh
 */
public class ViewDoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDoctorPanel
     */
    Person person;
    PatientDirectory patientDirectory;
    
    
    public ViewDoctorPanel(Person person, PatientDirectory patientDirectory) {
        initComponents();
        this.person = person;
        this.patientDirectory = patientDirectory;
        setDoctorProfileData();
        //WHY?
        getPatientData(jPatientChooser.getSelectedItem().toString());
        onChangeComboBox();
    }
    
     public void setDoctorProfileData() {
        txtDoctorNameValue.setText(this.person.getFirstName() + " " + this.person.getLastName());
        txtCommunityNameValue.setText(this.person.getHouse().getCommunity());
    }
     
    public void onChangeComboBox() {
        jPatientChooser.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                getPatientData(jPatientChooser.getSelectedItem().toString());
            }
        });
    }
    
    public void populateEncounterTable(Patient patient) {
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        model.setRowCount(0);

        ArrayList<Encounter> encounterList;

        encounterList = patient.getEncounterHistory().getEncounters();

        for (Encounter enc : encounterList) {
            Object[] row = new Object[7];
            row[0] = patient;
            row[1] = enc.getEncounterId();
            row[2] = enc.getDate();
            row[3] = enc.getVitalSigns().getHeartRate();
            row[4] = enc.getVitalSigns().getBloodPressure();
            row[5] = enc.getVitalSigns().getTemperature();
            row[6] = enc.getVitalSigns().getWeight();

            model.addRow(row);
        }
    }
    
    //POPULATING TABLE BASED ON CMB SELECTION
    public void getPatientData(String selectedPatient) {

        Patient patientObj = new Patient();

        for (Patient pa : patientDirectory.getPatients()) {
            if (pa.getName().equals(selectedPatient)) {
                patientObj = pa;
                break;
            }
        }

        populateEncounterTable(patientObj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDoctorNameValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCommunityNameValue = new javax.swing.JLabel();
        jPatientChooser = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVital = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jLabel1.setText("Doctor Name :");

        txtDoctorNameValue.setText("NA");

        jLabel2.setText("Community Name :");

        txtCommunityNameValue.setText("NA");

        jPatientChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PatientA", "PatientB", "PatientC", "PatientD" }));

        tblVital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Encounter ID", "Encounter Date", "Blood Pressure", "Heart Rate", "Temperature", "Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVital);

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDoctorNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCommunityNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jPatientChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnView)
                        .addGap(79, 79, 79)
                        .addComponent(btnDelete)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDoctorNameValue)
                    .addComponent(jLabel2)
                    .addComponent(txtCommunityNameValue))
                .addGap(18, 18, 18)
                .addComponent(jPatientChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblVital.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        //QUES-WHY?
        DoctorJFrame.setCreateDoctorPanel(person, patientDirectory, (Patient) model.getValueAt(selectedRowIndex, 0), selectedRowIndex);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblVital.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        patientDirectory.deletePatientEncounter((Patient) model.getValueAt(selectedRowIndex, 0), selectedRowIndex);
        JOptionPane.showMessageDialog(this, "Patient encounter deleted");
        //why getpatient data here?
        getPatientData(jPatientChooser.getSelectedItem().toString());
        DoctorJFrame.refreshCreateDoctorPanel(person, patientDirectory);
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jPatientChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVital;
    private javax.swing.JLabel txtCommunityNameValue;
    private javax.swing.JLabel txtDoctorNameValue;
    // End of variables declaration//GEN-END:variables
}
