/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
/**
 *
 * @author siddh
 */
public class ViewDoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDoctorPanel
     */
    Person person;
    PatientDirectory patientDirectory;
    PersonDirectory personDirectory;
    
    
    public ViewDoctorPanel(Person person, PatientDirectory patientDirectory, PersonDirectory personDirectory) {
        initComponents();
        this.person = person;
        this.patientDirectory = patientDirectory;
        this.personDirectory = personDirectory;
        setDoctorProfileData();
        constructDoctorPatients();
        
    }
    
    public void constructDoctorPatients() {
        for (Person p : personDirectory.getPersons()) {
            if ((p.getRoleType() == "Patient") && (p.getHouse().getCommunity()).equals(this.person.getHouse().getCommunity())) {
                jPatientChooser.addItem(p.getFirstName() + " " + p.getLastName());
            }
        }
        if (jPatientChooser.getSelectedItem() != null) {
            onChangeComboBox();
            getPatientData(jPatientChooser.getSelectedItem().toString());
        }
        else {
           JOptionPane.showMessageDialog(this, "No patients available to enter their encounter details");
        }
    }
    
     public void setDoctorProfileData() {
        txtDoctorNameValue.setText(this.person.getFirstName() + " " + this.person.getLastName());
        txtCommunityNameValue.setText(this.person.getHouse().getCommunity());
    }
     
    public void onChangeComboBox() {
        jPatientChooser.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                getPatientData(jPatientChooser.getSelectedItem().toString());
            }
        });
    }
    
    
    public void populateEncounterTable(Patient patient) {
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        model.setRowCount(0);

        ArrayList<Encounter> encounterList;

        encounterList = patient.getEncounterHistory().getEncounters();
        
        SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMMM dd, yyyy");

        for (Encounter enc : encounterList) {
            Object[] row = new Object[7];
            row[0] = patient;
            row[1] = enc.getEncounterId();
            row[2] = sdf.format(enc.getDate());
            row[3] = enc.getVitalSigns().getHeartRate();
            row[4] = enc.getVitalSigns().getBloodPressure();
            row[5] = enc.getVitalSigns().getTemperature();
            row[6] = enc.getVitalSigns().getWeight();

            model.addRow(row);
        }
    }
    
    //POPULATING TABLE BASED ON CMB SELECTION
    public void getPatientData(String selectedPatient) {

        Patient patientObj = new Patient();

        for (Patient pa : patientDirectory.getPatients()) {
            if (pa.getName().equals(selectedPatient)) {
                patientObj = pa;
                break;
            }
        }

        populateEncounterTable(patientObj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDoctorNameValue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCommunityNameValue = new javax.swing.JLabel();
        jPatientChooser = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVital = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Doctor Name :");

        txtDoctorNameValue.setText("NA");

        jLabel2.setText("Community Name :");

        txtCommunityNameValue.setText("NA");

        tblVital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Encounter ID", "Encounter Date", "Blood Pressure", "Heart Rate", "Temperature", "Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVital);

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("DOCTOR PAGE :");

        jLabel4.setText("Choose Patient :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnView)
                        .addGap(79, 79, 79)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jPatientChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDoctorNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCommunityNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDoctorNameValue)
                    .addComponent(jLabel2)
                    .addComponent(txtCommunityNameValue))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPatientChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnDelete))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblVital.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        //QUES-WHY?
        DoctorJFrame.setCreateDoctorPanel(person, patientDirectory, (Patient) model.getValueAt(selectedRowIndex, 0), selectedRowIndex);
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblVital.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblVital.getModel();
        patientDirectory.deletePatientEncounter((Patient) model.getValueAt(selectedRowIndex, 0), selectedRowIndex);
        JOptionPane.showMessageDialog(this, "Patient encounter deleted");
        //why getpatient data here?
        getPatientData(jPatientChooser.getSelectedItem().toString());
        DoctorJFrame.refreshCreateDoctorPanel(person, patientDirectory);
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jPatientChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVital;
    private javax.swing.JLabel txtCommunityNameValue;
    private javax.swing.JLabel txtDoctorNameValue;
    // End of variables declaration//GEN-END:variables
}
